export const buildAutopsyEmailHtml = (runId: string, workflowId: string, success: boolean, report: string) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #e4e4e7; }
  h1 { color: #18181b; font-size: 24px; margin-bottom: 5px; }
  .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; margin-bottom: 20px; }
  .success { background-color: #dcfce7; color: #166534; }
  .failed { background-color: #fee2e2; color: #991b1b; }
  .metadata { font-size: 14px; color: #52525b; margin-bottom: 20px; padding-bottom: 20px; border-bottom: 1px solid #e4e4e7; }
  .report { background-color: #f8fafc; padding: 15px; border-left: 4px solid #3b82f6; font-size: 14px; color: #334155; white-space: pre-wrap; margin-top: 20px; }
  .footer { margin-top: 30px; font-size: 12px; color: #a1a1aa; text-align: center; }
</style>
</head>
<body>
  <div class="container">
    <h1>FlowSentrix Autopsy Report</h1>
    <div class="badge ${success ? 'success' : 'failed'}">${success ? 'RESOLVED' : 'ESCALATED TO HITL'}</div>
    
    <div class="metadata">
      <strong>Run ID:</strong> ${runId}<br>
      <strong>Workflow ID:</strong> ${workflowId}<br>
      <strong>Date:</strong> ${new Date().toISOString()}
    </div>

    <h3>LLM Diagnostic Report</h3>
    <div class="report">${report}</div>
    
    <div class="footer">
      This is an automated report generated by the FlowSentrix Self-Healing Pipeline.
    </div>
  </div>
</body>
</html>
`;

export const buildHitlEmailHtml = (runId: string, stepIndex: number, hitlUrl: string, briefing: string) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #fee2e2; }
  h1 { color: #991b1b; font-size: 24px; margin-bottom: 20px; }
  .metadata { font-size: 14px; color: #52525b; margin-bottom: 20px; }
  .briefing { background-color: #fef2f2; padding: 15px; border-left: 4px solid #ef4444; font-size: 14px; color: #991b1b; margin-top: 20px; margin-bottom: 30px; }
  .btn { display: inline-block; background-color: #ef4444; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; }
</style>
</head>
<body>
  <div class="container">
    <h1>⚠️ Human Decision Required</h1>
    
    <div class="metadata">
      An agent in <strong>Run ${runId}</strong> has exhausted all self-healing retries at <strong>Step ${stepIndex}</strong>.
    </div>

    <div class="briefing">
      <strong>Briefing:</strong><br>
      ${briefing}
    </div>
    
    <a href="${hitlUrl}" class="btn">Review & Decide</a>
  </div>
</body>
</html>
`;

export const buildOnboardingEmailHtml = (name: string, role: string) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #e4e4e7; text-align: center; }
  h1 { color: #18181b; font-size: 28px; margin-bottom: 10px; }
  p { font-size: 16px; color: #52525b; line-height: 1.5; margin-bottom: 20px; }
  .btn { display: inline-block; background-color: #2563eb; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; }
</style>
</head>
<body>
  <div class="container">
    <h1>Welcome to the team, ${name}! 🎉</h1>
    <p>We're thrilled to have you join us as our newest <strong>${role}</strong>.</p>
    <p>Your AI onboarding agent has provisioned your accounts, set up your repositories, and prepared your starter materials. You can find your onboarding packet attached to this email.</p>
    <br>
    <a href="https://example.com/getting-started" class="btn">View Onboarding Dashboard</a>
  </div>
</body>
</html>
`;
