export const buildAutopsyEmailHtml = (runId: string, workflowId: string, success: boolean, report: string) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #e4e4e7; }
  h1 { color: #18181b; font-size: 24px; margin-bottom: 5px; }
  .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; margin-bottom: 20px; }
  .success { background-color: #dcfce7; color: #166534; }
  .failed { background-color: #fee2e2; color: #991b1b; }
  .metadata { font-size: 14px; color: #52525b; margin-bottom: 20px; padding-bottom: 20px; border-bottom: 1px solid #e4e4e7; }
  .report { background-color: #f8fafc; padding: 15px; border-left: 4px solid #3b82f6; font-size: 14px; color: #334155; white-space: pre-wrap; margin-top: 20px; }
  .footer { margin-top: 30px; font-size: 12px; color: #a1a1aa; text-align: center; }
</style>
</head>
<body>
  <div class="container">
    <h1>FlowSentrix Autopsy Report</h1>
    <div class="badge ${success ? 'success' : 'failed'}">${success ? 'RESOLVED' : 'ESCALATED TO HITL'}</div>
    
    <div class="metadata">
      <strong>Run ID:</strong> ${runId}<br>
      <strong>Workflow ID:</strong> ${workflowId}<br>
      <strong>Date:</strong> ${new Date().toISOString()}
    </div>

    <h3>LLM Diagnostic Report</h3>
    <div class="report">${report}</div>
    
    <div class="footer">
      This is an automated report generated by the FlowSentrix Self-Healing Pipeline.
    </div>
  </div>
</body>
</html>
`;

export const buildHitlEmailHtml = (runId: string, stepIndex: number, hitlUrl: string, briefing: string) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; border: 1px solid #fee2e2; }
  h1 { color: #991b1b; font-size: 24px; margin-bottom: 20px; }
  .metadata { font-size: 14px; color: #52525b; margin-bottom: 20px; }
  .briefing { background-color: #fef2f2; padding: 15px; border-left: 4px solid #ef4444; font-size: 14px; color: #991b1b; margin-top: 20px; margin-bottom: 30px; }
  .btn { display: inline-block; background-color: #ef4444; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; }
</style>
</head>
<body>
  <div class="container">
    <h1>⚠️ Human Decision Required</h1>
    
    <div class="metadata">
      An agent in <strong>Run ${runId}</strong> has exhausted all self-healing retries at <strong>Step ${stepIndex}</strong>.
    </div>

    <div class="briefing">
      <strong>Briefing:</strong><br>
      ${briefing}
    </div>
    
    <a href="${hitlUrl}" class="btn">Review & Decide</a>
  </div>
</body>
</html>
`;

export const buildOnboardingEmailHtml = (name: string, role: string) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 20px; }
  .container { max-width: 640px; margin: 0 auto; background: #ffffff; padding: 28px; border-radius: 10px; border: 1px solid #e4e4e7; }
  h1 { color: #18181b; font-size: 24px; margin: 0 0 8px; }
  .sub { font-size: 14px; color: #52525b; margin: 0 0 18px; line-height: 1.6; }
  .card { background: #fafafa; border: 1px solid #e4e4e7; border-radius: 10px; padding: 16px; margin: 14px 0; }
  .label { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: #71717a; margin-bottom: 8px; font-weight: 700; }
  .row { display: flex; gap: 12px; flex-wrap: wrap; }
  .pill { display: inline-block; background: #f4f4f5; border: 1px solid #e4e4e7; border-radius: 999px; padding: 6px 10px; font-size: 13px; color: #18181b; }
  ul { margin: 10px 0 0; padding-left: 18px; color: #3f3f46; font-size: 14px; line-height: 1.7; }
  li { margin: 6px 0; }
  a { color: #2563eb; }
  .btn { display: inline-block; background-color: #111827; color: #ffffff !important; padding: 12px 16px; text-decoration: none; border-radius: 8px; font-weight: 700; font-size: 14px; }
  .btnRow { margin-top: 14px; }
  .footer { margin-top: 18px; color: #71717a; font-size: 12px; line-height: 1.6; }
</style>
</head>
<body>
  <div class="container">
    <h1>Welcome aboard, ${name}</h1>
    <p class="sub">
      Your onboarding is ready. This email includes the key next steps and your starter checklist.
    </p>

    <div class="card">
      <div class="label">Role</div>
      <div class="row">
        <span class="pill"><strong>${role}</strong></span>
        <span class="pill">Status: <strong>Provisioning complete</strong></span>
      </div>
    </div>

    <div class="card">
      <div class="label">First-day checklist</div>
      <ul>
        <li>Open the attached onboarding packet and review your team + access details.</li>
        <li>Log in to Slack and introduce yourself in <strong>#introductions</strong>.</li>
        <li>Confirm access to email + calendar and set your working hours.</li>
        <li>Schedule your 15-minute setup call with your manager.</li>
      </ul>
    </div>

    <div class="card">
      <div class="label">Helpful links</div>
      <ul>
        <li>Getting started: <a href="https://example.com/getting-started">https://example.com/getting-started</a></li>
        <li>Company handbook: <a href="https://example.com/handbook">https://example.com/handbook</a></li>
        <li>IT support: <a href="https://example.com/it">https://example.com/it</a></li>
      </ul>
      <div class="btnRow">
        <a href="https://example.com/getting-started" class="btn">Open onboarding dashboard</a>
      </div>
    </div>

    <div class="footer">
      If anything looks wrong (missing access, wrong role/title, or incorrect details), reply to this email and the ops team will fix it.
    </div>
  </div>
</body>
</html>
`;
